### ISSUE TITLE
I want to reproduce

### ISSUE THREAD

**Issue by wonchul-kim** [haruishi43/boundary_boost_mmseg#2]
Thank you for your share.

I want to reproduce your papaer. 
However, there is nothing on https://github.com/haruishi43/boundary_boost_mmseg/tree/main/.readme
And There is no weights/pretrained wieghts.
Could you share?

**Comment by haruishi43** [comment]
Hi, which experiment did you want to reproduce?
I forgot to update the readme since I could not release all of the experiments. However, I do have configs to apply SBCB to deeplabv3+, pspnet, and segformer. You really just need to follow the setup and run the configs like you would for mmseg (e.g. `./tools/dist_train.sh path/to/config.py 1`).
As for the weights, I have no access to the severs where the experiments were done.
